version: '3.7'
services:
    minio-server:
        image: minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
        ports:
            - 9090:9000
            - 8080:8080
        environment: 
            - MINIO_ROOT_USER=minioadminn
            - MINIO_ROOT_PASSWORD=minioadminn
        volumes:
            - ./data:/export
        command: minio server /export --console-address 0.0.0.0:8080
