
services:
    minio-server:
        image: minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
        ports:
            - 9090:9000
            - 8080:8080
        environment: 
            - MINIO_ROOT_USER=minioadminn
            - MINIO_ROOT_PASSWORD=minioadminn
        volumes:
            - ./data:/export
        command: minio server /export --console-address 0.0.0.0:8080

    postgres:
        image: postgres:15-alpine
        container_name: s3xplorer-postgres
        environment:
            POSTGRES_DB: s3xplorer
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5