# https://taskfile.dev
version: '3'
vars:
  BINFILE: s3xplorer

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - go generate ./...
      - CGO_ENABLED=0 go build .

  linter:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  minio:
    desc: "Launch minio server"
    dir: conf-examples
    cmds:
      - docker compose up -d

  run:
    desc: "Run the binary with minio server"
    deps: 
    - minio
    cmds:
      - go run . -f conf-examples/config-minio.yaml

  run-postgres:
    desc: "Run the binary with PostgreSQL backend and minio server"
    deps:
    - postgres-stack
    - db-migrate
    cmds:
      - go run . -f conf-examples/config-postgres.yaml

  postgres-stack:
    desc: "Start PostgreSQL and MinIO with Docker Compose"
    cmds:
      - docker compose -f docker-compose.postgres.yml up -d

  postgres-stack-down:
    desc: "Stop PostgreSQL and MinIO stack"
    cmds:
      - docker compose -f docker-compose.postgres.yml down

  image:
    desc: "Build/push the docker image version latest"
    cmds:
      - docker build . -t ghcr.io/sgaunet/{{.BINFILE}}:latest --push

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot

  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

    