# https://taskfile.dev
version: '3'
vars:
  BINFILE: s3xplorer
  TAILWIND_VERSION: v3.4.17
  TAILWIND_OS: '{{if eq OS "darwin"}}macos{{else if eq OS "windows"}}windows{{else}}linux{{end}}'
  TAILWIND_ARCH: '{{if eq ARCH "amd64"}}x64{{else}}arm64{{end}}'
  TAILWIND_EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  tailwind:download:
    desc: "Download Tailwind CSS standalone binary"
    silent: true
    cmds:
      - mkdir -p bin
      - curl -sL -o bin/tailwindcss{{.TAILWIND_EXT}} https://github.com/tailwindlabs/tailwindcss/releases/download/{{.TAILWIND_VERSION}}/tailwindcss-{{.TAILWIND_OS}}-{{.TAILWIND_ARCH}}{{.TAILWIND_EXT}}
      - chmod +x bin/tailwindcss{{.TAILWIND_EXT}}
    status:
      - test -f bin/tailwindcss{{.TAILWIND_EXT}}

  css:build:
    desc: "Build Tailwind CSS"
    deps:
      - tailwind:download
    sources:
      - pkg/views/**/*.templ
      - pkg/views/static/src/input.css
    generates:
      - pkg/views/static/app.css
    cmds:
      - ./bin/tailwindcss{{.TAILWIND_EXT}} -i pkg/views/static/src/input.css -o pkg/views/static/app.css --minify

  css:watch:
    desc: "Watch and rebuild Tailwind CSS"
    deps:
      - tailwind:download
    sources:
      - pkg/views/**/*.templ
      - pkg/views/static/src/input.css
    cmds:
      - ./bin/tailwindcss{{.TAILWIND_EXT}} -i pkg/views/static/src/input.css -o pkg/views/static/app.css --watch

  build:
    desc: "Build the binary"
    deps:
      - css:build
    cmds:
      - go mod download
      - go generate ./...
      - CGO_ENABLED=0 go build .

  lint:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  minio:
    desc: "Launch minio server"
    dir: conf-examples
    cmds:
      - docker compose up -d

  run:
    desc: "Run the binary with minio server"
    deps: 
    - minio
    cmds:
      - go generate ./...
      - go run . -f conf-examples/config-minio.yaml

  image:
    desc: "Build docker image"
    deps: 
    - snapshot
    cmds:
      - docker push ghcr.io/sgaunet/s3xplorer:latest-amd64
      - docker tag  ghcr.io/sgaunet/s3xplorer:latest-amd64 ghcr.io/sgaunet/s3xplorer:latest
      - docker push ghcr.io/sgaunet/s3xplorer:latest

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot

  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean

    